// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20200829100431_CreateProductsDB")]
    partial class CreateProductsDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductAPI.Models.ProductCopies", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductsID")
                        .HasColumnType("int");

                    b.HasKey("SerialNumber");

                    b.HasIndex("ProductsID");

                    b.ToTable("ProductCopies");

                    b.HasData(
                        new
                        {
                            SerialNumber = "BOOK100",
                            ProductsID = 1
                        },
                        new
                        {
                            SerialNumber = "BOOK200",
                            ProductsID = 1
                        },
                        new
                        {
                            SerialNumber = "BOOK300",
                            ProductsID = 1
                        },
                        new
                        {
                            SerialNumber = "BOARDGAME100",
                            ProductsID = 2
                        },
                        new
                        {
                            SerialNumber = "BOARDGAME200",
                            ProductsID = 2
                        },
                        new
                        {
                            SerialNumber = "BOARDGAME300",
                            ProductsID = 2
                        },
                        new
                        {
                            SerialNumber = "MACBOOK100",
                            ProductsID = 3
                        },
                        new
                        {
                            SerialNumber = "MACBOOK200",
                            ProductsID = 3
                        },
                        new
                        {
                            SerialNumber = "MACBOOK300",
                            ProductsID = 3
                        },
                        new
                        {
                            SerialNumber = "GUITAR100",
                            ProductsID = 4
                        },
                        new
                        {
                            SerialNumber = "GUITAR200",
                            ProductsID = 4
                        },
                        new
                        {
                            SerialNumber = "GUITAR300",
                            ProductsID = 4
                        });
                });

            modelBuilder.Entity("ProductAPI.Models.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CopyCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CopyCount = 3,
                            Description = "Cool Book",
                            Name = "Book"
                        },
                        new
                        {
                            ID = 2,
                            CopyCount = 3,
                            Description = "Splendor",
                            Name = "BoardGame"
                        },
                        new
                        {
                            ID = 3,
                            CopyCount = 3,
                            Description = "Arbets dator",
                            Name = "MacBook"
                        },
                        new
                        {
                            ID = 4,
                            CopyCount = 3,
                            Description = "Hög kvalitet",
                            Name = "Guitar"
                        });
                });

            modelBuilder.Entity("ProductAPI.Models.ProductCopies", b =>
                {
                    b.HasOne("ProductAPI.Models.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
